provider: pihole
policy: upsert-only
txtOwnerId: "homelab"
pihole:
  server: http://pihole-web.pihole-system.svc.cluster.local
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: admin
extraArgs:
  pihole-api-version: 6
serviceAccount:
  create: true
  name: "external-dns"
ingressClassFilters:
  - nginx-internal
