---
image:
  tag: "2025.07.1"
DNS1: 1.1.1.1
DNS2: ""
persistentVolumeClaim:
  enabled: true
admin:
  existingSecret: "pihole-password"
  passwordKey: "admin"
ingress:
  ingressClassName: nginx-internal
  enabled: true
  hosts:
    - "pihole.lab"
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
serviceWeb:
  loadBalancerIP: 192.168.50.210
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.50.210
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
